name: start github actions learing
on: 
  push:
    branches:
      - main
      - dev
      - sit
      - uat
jobs:
  example:
    runs-on: ubuntu-latest
    name: Example job
    steps:
      - name: hello world
        uses: Bluezzydev/pipeline-template/test@main
        with: 
          user_name: 'GitHub Actions'
          age: '5'